# Generated by Django 5.1.1 on 2025-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GK', 'Greek'), ('MX', 'Maxican'), ('FF', 'Fast Food'), ('OT', 'Other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
